#index:
#    path: /
#    controller: App\Controller\DefaultController::index


test:
  path: /test
  controller: App\Controller\AdminController::test

some:
  path: /some
  controller: App\Controller\SomeController::index

posts:
  path: /posts/{page?}
  controller:  App\Controller\PostController::index
  methods:  [GET]

post_create:
  path: /create
  controller: App\Controller\PostController::create
  methods:  [GET]

post_store:
  path: /create
  controller: App\Controller\PostController::store
  methods:  [POST]

post_show:
  path: /show/{id}
  controller: App\Controller\PostController::show
  methods:  [GET]

post_edit:
  path: /edit/{id}
  controller: App\Controller\PostController::edit
  methods:  [GET]

post_update:
  path: /update/{id}
  controller: App\Controller\PostController::update
  methods:  [POST]

post_delete:
  path: /delete/{id}
  controller: App\Controller\PostController::delete
  methods:  [GET]

users:
  path: /users/show/{page?}
  controller: App\Controller\UserController::index
  methods:  [GET]

user_create:
  path: /users/create
  controller: App\Controller\UserController::create
  methods:  [GET]

user_store:
  path: /users/create
  controller: App\Controller\UserController::store
  methods:  [POST]

user_single:
  path: /users/single/{id}
  controller: App\Controller\UserController::show
  methods:  [GET]